sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t vansh912/docker-frontend -f Dockerfile.dev .


script:
  # frontend-web-1 is the container name
  - docker run -e CI=true vansh912/docker-frontend npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: docker-react
  env: "Docker-react-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-238951270020"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
