sudo: required
services:
  - docker

before_install:
  - npm install 

script:
  - docker build -t vansh912/docker-frontend -f Dockerfile.dev . 
  - docker run vansh912/docker-frontend npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: docker-react
  env: "Docker-react-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-238951270020"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
