# Specify a base image
FROM node:alpine

WORKDIR '/app'

# install some dependencies
COPY package*.json ./

RUN npm install

RUN npm run build

COPY . .

FROM nginx
EXPOSE 80

RUN apk add --no-cache npm

# Default command
CMD ["npm", "run", "dev"]
